// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.6
// source: upi/unblockvpa.proto

package upi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnblockVPARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	BlockType     string                 `protobuf:"bytes,2,opt,name=block_type,json=blockType,proto3" json:"block_type,omitempty"`
	BlockValue    string                 `protobuf:"bytes,3,opt,name=block_value,json=blockValue,proto3" json:"block_value,omitempty"`
	ProfileId     string                 `protobuf:"bytes,4,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockVPARequest) Reset() {
	*x = UnblockVPARequest{}
	mi := &file_upi_unblockvpa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockVPARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockVPARequest) ProtoMessage() {}

func (x *UnblockVPARequest) ProtoReflect() protoreflect.Message {
	mi := &file_upi_unblockvpa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockVPARequest.ProtoReflect.Descriptor instead.
func (*UnblockVPARequest) Descriptor() ([]byte, []int) {
	return file_upi_unblockvpa_proto_rawDescGZIP(), []int{0}
}

func (x *UnblockVPARequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UnblockVPARequest) GetBlockType() string {
	if x != nil {
		return x.BlockType
	}
	return ""
}

func (x *UnblockVPARequest) GetBlockValue() string {
	if x != nil {
		return x.BlockValue
	}
	return ""
}

func (x *UnblockVPARequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *UnblockVPARequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type UnblockVPAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockVPAResponse) Reset() {
	*x = UnblockVPAResponse{}
	mi := &file_upi_unblockvpa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockVPAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockVPAResponse) ProtoMessage() {}

func (x *UnblockVPAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upi_unblockvpa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockVPAResponse.ProtoReflect.Descriptor instead.
func (*UnblockVPAResponse) Descriptor() ([]byte, []int) {
	return file_upi_unblockvpa_proto_rawDescGZIP(), []int{1}
}

func (x *UnblockVPAResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UnblockVPAResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_upi_unblockvpa_proto protoreflect.FileDescriptor

var file_upi_unblockvpa_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x75, 0x70, 0x69, 0x2f, 0x75, 0x6e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x76, 0x70, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x75, 0x70, 0x69, 0x2e, 0x75, 0x6e, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x56, 0x50, 0x41, 0x22, 0xa7, 0x01, 0x0a, 0x11, 0x75, 0x6e, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x56, 0x50, 0x41, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x22, 0x46, 0x0a, 0x12, 0x75, 0x6e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x56, 0x50, 0x41, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_upi_unblockvpa_proto_rawDescOnce sync.Once
	file_upi_unblockvpa_proto_rawDescData []byte
)

func file_upi_unblockvpa_proto_rawDescGZIP() []byte {
	file_upi_unblockvpa_proto_rawDescOnce.Do(func() {
		file_upi_unblockvpa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upi_unblockvpa_proto_rawDesc), len(file_upi_unblockvpa_proto_rawDesc)))
	})
	return file_upi_unblockvpa_proto_rawDescData
}

var file_upi_unblockvpa_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_upi_unblockvpa_proto_goTypes = []any{
	(*UnblockVPARequest)(nil),  // 0: upi.unblockVPA.unblockVPARequest
	(*UnblockVPAResponse)(nil), // 1: upi.unblockVPA.unblockVPAResponse
}
var file_upi_unblockvpa_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_upi_unblockvpa_proto_init() }
func file_upi_unblockvpa_proto_init() {
	if File_upi_unblockvpa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upi_unblockvpa_proto_rawDesc), len(file_upi_unblockvpa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_upi_unblockvpa_proto_goTypes,
		DependencyIndexes: file_upi_unblockvpa_proto_depIdxs,
		MessageInfos:      file_upi_unblockvpa_proto_msgTypes,
	}.Build()
	File_upi_unblockvpa_proto = out.File
	file_upi_unblockvpa_proto_goTypes = nil
	file_upi_unblockvpa_proto_depIdxs = nil
}
