// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.6
// source: upi/upinumberoperations.proto

package upi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpiNumberOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vpa           string                 `protobuf:"bytes,1,opt,name=vpa,proto3" json:"vpa,omitempty"`
	UpiNumber     string                 `protobuf:"bytes,2,opt,name=upi_number,json=upiNumber,proto3" json:"upi_number,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	ProfileId     string                 `protobuf:"bytes,4,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Mobile        string                 `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`
	UserConsent   string                 `protobuf:"bytes,7,opt,name=user_consent,json=userConsent,proto3" json:"user_consent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpiNumberOperationsRequest) Reset() {
	*x = UpiNumberOperationsRequest{}
	mi := &file_upi_upinumberoperations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpiNumberOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpiNumberOperationsRequest) ProtoMessage() {}

func (x *UpiNumberOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upi_upinumberoperations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpiNumberOperationsRequest.ProtoReflect.Descriptor instead.
func (*UpiNumberOperationsRequest) Descriptor() ([]byte, []int) {
	return file_upi_upinumberoperations_proto_rawDescGZIP(), []int{0}
}

func (x *UpiNumberOperationsRequest) GetVpa() string {
	if x != nil {
		return x.Vpa
	}
	return ""
}

func (x *UpiNumberOperationsRequest) GetUpiNumber() string {
	if x != nil {
		return x.UpiNumber
	}
	return ""
}

func (x *UpiNumberOperationsRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *UpiNumberOperationsRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *UpiNumberOperationsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UpiNumberOperationsRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UpiNumberOperationsRequest) GetUserConsent() string {
	if x != nil {
		return x.UserConsent
	}
	return ""
}

type UpiNumberOperationsData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UpiNumber       string                 `protobuf:"bytes,1,opt,name=upi_number,json=upiNumber,proto3" json:"upi_number,omitempty"`
	UpiNumberStatus *string                `protobuf:"bytes,2,opt,name=upi_number_status,json=upiNumberStatus,proto3,oneof" json:"upi_number_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpiNumberOperationsData) Reset() {
	*x = UpiNumberOperationsData{}
	mi := &file_upi_upinumberoperations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpiNumberOperationsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpiNumberOperationsData) ProtoMessage() {}

func (x *UpiNumberOperationsData) ProtoReflect() protoreflect.Message {
	mi := &file_upi_upinumberoperations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpiNumberOperationsData.ProtoReflect.Descriptor instead.
func (*UpiNumberOperationsData) Descriptor() ([]byte, []int) {
	return file_upi_upinumberoperations_proto_rawDescGZIP(), []int{1}
}

func (x *UpiNumberOperationsData) GetUpiNumber() string {
	if x != nil {
		return x.UpiNumber
	}
	return ""
}

func (x *UpiNumberOperationsData) GetUpiNumberStatus() string {
	if x != nil && x.UpiNumberStatus != nil {
		return *x.UpiNumberStatus
	}
	return ""
}

type UpiNumberOperationsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UpiNumberOperationsData `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpiNumberOperationsResponse) Reset() {
	*x = UpiNumberOperationsResponse{}
	mi := &file_upi_upinumberoperations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpiNumberOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpiNumberOperationsResponse) ProtoMessage() {}

func (x *UpiNumberOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upi_upinumberoperations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpiNumberOperationsResponse.ProtoReflect.Descriptor instead.
func (*UpiNumberOperationsResponse) Descriptor() ([]byte, []int) {
	return file_upi_upinumberoperations_proto_rawDescGZIP(), []int{2}
}

func (x *UpiNumberOperationsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpiNumberOperationsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpiNumberOperationsResponse) GetData() *UpiNumberOperationsData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_upi_upinumberoperations_proto protoreflect.FileDescriptor

var file_upi_upinumberoperations_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x75, 0x70, 0x69, 0x2f, 0x75, 0x70, 0x69, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x75, 0x70, 0x69, 0x2e, 0x75, 0x70, 0x69, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xe2, 0x01, 0x0a, 0x1a, 0x75, 0x70, 0x69,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x70, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x70, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x69,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x70, 0x69, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x74, 0x22, 0x7f, 0x0a,
	0x17, 0x75, 0x70, 0x69, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x69, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70,
	0x69, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x11, 0x75, 0x70, 0x69, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0f, 0x75, 0x70, 0x69, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x75, 0x70, 0x69,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xa3,
	0x01, 0x0a, 0x1b, 0x75, 0x70, 0x69, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x49, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x75, 0x70, 0x69, 0x2e, 0x75, 0x70, 0x69, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x75, 0x70, 0x69, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_upi_upinumberoperations_proto_rawDescOnce sync.Once
	file_upi_upinumberoperations_proto_rawDescData []byte
)

func file_upi_upinumberoperations_proto_rawDescGZIP() []byte {
	file_upi_upinumberoperations_proto_rawDescOnce.Do(func() {
		file_upi_upinumberoperations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upi_upinumberoperations_proto_rawDesc), len(file_upi_upinumberoperations_proto_rawDesc)))
	})
	return file_upi_upinumberoperations_proto_rawDescData
}

var file_upi_upinumberoperations_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_upi_upinumberoperations_proto_goTypes = []any{
	(*UpiNumberOperationsRequest)(nil),  // 0: upi.upiNumberOperations.upiNumberOperationsRequest
	(*UpiNumberOperationsData)(nil),     // 1: upi.upiNumberOperations.upiNumberOperationsData
	(*UpiNumberOperationsResponse)(nil), // 2: upi.upiNumberOperations.upiNumberOperationsResponse
}
var file_upi_upinumberoperations_proto_depIdxs = []int32{
	1, // 0: upi.upiNumberOperations.upiNumberOperationsResponse.data:type_name -> upi.upiNumberOperations.upiNumberOperationsData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_upi_upinumberoperations_proto_init() }
func file_upi_upinumberoperations_proto_init() {
	if File_upi_upinumberoperations_proto != nil {
		return
	}
	file_upi_upinumberoperations_proto_msgTypes[1].OneofWrappers = []any{}
	file_upi_upinumberoperations_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upi_upinumberoperations_proto_rawDesc), len(file_upi_upinumberoperations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_upi_upinumberoperations_proto_goTypes,
		DependencyIndexes: file_upi_upinumberoperations_proto_depIdxs,
		MessageInfos:      file_upi_upinumberoperations_proto_msgTypes,
	}.Build()
	File_upi_upinumberoperations_proto = out.File
	file_upi_upinumberoperations_proto_goTypes = nil
	file_upi_upinumberoperations_proto_depIdxs = nil
}
