// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: loans/foreclosepayment.proto

package loans

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForeclosePaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount     int32                           `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Customerid int32                           `protobuf:"varint,2,opt,name=customerid,proto3" json:"customerid,omitempty"`
	LoanId     []int32                         `protobuf:"varint,3,rep,packed,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	Mode       string                          `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	AddOns     []*ForeclosePaymentRequestAddOn `protobuf:"bytes,5,rep,name=add_ons,json=addOns,proto3" json:"add_ons,omitempty"`
}

func (x *ForeclosePaymentRequest) Reset() {
	*x = ForeclosePaymentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loans_foreclosepayment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForeclosePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeclosePaymentRequest) ProtoMessage() {}

func (x *ForeclosePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loans_foreclosepayment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeclosePaymentRequest.ProtoReflect.Descriptor instead.
func (*ForeclosePaymentRequest) Descriptor() ([]byte, []int) {
	return file_loans_foreclosepayment_proto_rawDescGZIP(), []int{0}
}

func (x *ForeclosePaymentRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ForeclosePaymentRequest) GetCustomerid() int32 {
	if x != nil {
		return x.Customerid
	}
	return 0
}

func (x *ForeclosePaymentRequest) GetLoanId() []int32 {
	if x != nil {
		return x.LoanId
	}
	return nil
}

func (x *ForeclosePaymentRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ForeclosePaymentRequest) GetAddOns() []*ForeclosePaymentRequestAddOn {
	if x != nil {
		return x.AddOns
	}
	return nil
}

type ForeclosePaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RedirectUrl string  `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	Message     *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	OrderId     string  `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *ForeclosePaymentResponse) Reset() {
	*x = ForeclosePaymentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loans_foreclosepayment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForeclosePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeclosePaymentResponse) ProtoMessage() {}

func (x *ForeclosePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loans_foreclosepayment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeclosePaymentResponse.ProtoReflect.Descriptor instead.
func (*ForeclosePaymentResponse) Descriptor() ([]byte, []int) {
	return file_loans_foreclosepayment_proto_rawDescGZIP(), []int{1}
}

func (x *ForeclosePaymentResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *ForeclosePaymentResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ForeclosePaymentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ForeclosePaymentRequestAddOn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	PlanId   string `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Amount   int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	MetaData string `protobuf:"bytes,4,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
}

func (x *ForeclosePaymentRequestAddOn) Reset() {
	*x = ForeclosePaymentRequestAddOn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loans_foreclosepayment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForeclosePaymentRequestAddOn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeclosePaymentRequestAddOn) ProtoMessage() {}

func (x *ForeclosePaymentRequestAddOn) ProtoReflect() protoreflect.Message {
	mi := &file_loans_foreclosepayment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeclosePaymentRequestAddOn.ProtoReflect.Descriptor instead.
func (*ForeclosePaymentRequestAddOn) Descriptor() ([]byte, []int) {
	return file_loans_foreclosepayment_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ForeclosePaymentRequestAddOn) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ForeclosePaymentRequestAddOn) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ForeclosePaymentRequestAddOn) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ForeclosePaymentRequestAddOn) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

var File_loans_foreclosepayment_proto protoreflect.FileDescriptor

var file_loans_foreclosepayment_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6c, 0x6f, 0x61, 0x6e, 0x73, 0x2f, 0x66, 0x6f, 0x72, 0x65, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x6c, 0x6f, 0x61, 0x6e, 0x73, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xbb, 0x02, 0x0a, 0x17, 0x66, 0x6f, 0x72, 0x65, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x6f,
	0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x6f, 0x61,
	0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x4f, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x5f, 0x6f,
	0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x6c, 0x6f, 0x61, 0x6e, 0x73,
	0x2e, 0x66, 0x6f, 0x72, 0x65, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x61, 0x64, 0x64, 0x5f, 0x6f, 0x6e,
	0x52, 0x06, 0x61, 0x64, 0x64, 0x4f, 0x6e, 0x73, 0x1a, 0x6a, 0x0a, 0x06, 0x61, 0x64, 0x64, 0x5f,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x83, 0x01, 0x0a, 0x18, 0x66, 0x6f, 0x72, 0x65, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x42, 0x0a,
	0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_loans_foreclosepayment_proto_rawDescOnce sync.Once
	file_loans_foreclosepayment_proto_rawDescData = file_loans_foreclosepayment_proto_rawDesc
)

func file_loans_foreclosepayment_proto_rawDescGZIP() []byte {
	file_loans_foreclosepayment_proto_rawDescOnce.Do(func() {
		file_loans_foreclosepayment_proto_rawDescData = protoimpl.X.CompressGZIP(file_loans_foreclosepayment_proto_rawDescData)
	})
	return file_loans_foreclosepayment_proto_rawDescData
}

var file_loans_foreclosepayment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_loans_foreclosepayment_proto_goTypes = []interface{}{
	(*ForeclosePaymentRequest)(nil),      // 0: loans.foreclosepayment.foreclosePaymentRequest
	(*ForeclosePaymentResponse)(nil),     // 1: loans.foreclosepayment.foreclosePaymentResponse
	(*ForeclosePaymentRequestAddOn)(nil), // 2: loans.foreclosepayment.foreclosePaymentRequest.add_on
}
var file_loans_foreclosepayment_proto_depIdxs = []int32{
	2, // 0: loans.foreclosepayment.foreclosePaymentRequest.add_ons:type_name -> loans.foreclosepayment.foreclosePaymentRequest.add_on
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_loans_foreclosepayment_proto_init() }
func file_loans_foreclosepayment_proto_init() {
	if File_loans_foreclosepayment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_loans_foreclosepayment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForeclosePaymentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loans_foreclosepayment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForeclosePaymentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loans_foreclosepayment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForeclosePaymentRequestAddOn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_loans_foreclosepayment_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_loans_foreclosepayment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_loans_foreclosepayment_proto_goTypes,
		DependencyIndexes: file_loans_foreclosepayment_proto_depIdxs,
		MessageInfos:      file_loans_foreclosepayment_proto_msgTypes,
	}.Build()
	File_loans_foreclosepayment_proto = out.File
	file_loans_foreclosepayment_proto_rawDesc = nil
	file_loans_foreclosepayment_proto_goTypes = nil
	file_loans_foreclosepayment_proto_depIdxs = nil
}
