// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.6
// source: loans/getbilldetails.proto

package loans

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBillDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillDetailsRequest) Reset() {
	*x = GetBillDetailsRequest{}
	mi := &file_loans_getbilldetails_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillDetailsRequest) ProtoMessage() {}

func (x *GetBillDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loans_getbilldetails_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetBillDetailsRequest) Descriptor() ([]byte, []int) {
	return file_loans_getbilldetails_proto_rawDescGZIP(), []int{0}
}

type GetBillDetailsResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Data          []*GetBillDetailsResponse_Field `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillDetailsResponse) Reset() {
	*x = GetBillDetailsResponse{}
	mi := &file_loans_getbilldetails_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillDetailsResponse) ProtoMessage() {}

func (x *GetBillDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loans_getbilldetails_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetBillDetailsResponse) Descriptor() ([]byte, []int) {
	return file_loans_getbilldetails_proto_rawDescGZIP(), []int{1}
}

func (x *GetBillDetailsResponse) GetData() []*GetBillDetailsResponse_Field {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetBillDetailsResponse_Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BillAmount    int32                  `protobuf:"varint,1,opt,name=bill_amount,json=billAmount,proto3" json:"bill_amount,omitempty"`
	BillDate      string                 `protobuf:"bytes,2,opt,name=bill_date,json=billDate,proto3" json:"bill_date,omitempty"`
	Principal     int32                  `protobuf:"varint,3,opt,name=principal,proto3" json:"principal,omitempty"`
	Interest      int32                  `protobuf:"varint,4,opt,name=interest,proto3" json:"interest,omitempty"`
	InstId        int32                  `protobuf:"varint,5,opt,name=inst_id,json=instId,proto3" json:"inst_id,omitempty"`
	Penalty       int32                  `protobuf:"varint,6,opt,name=penalty,proto3" json:"penalty,omitempty"`
	IsVisible     bool                   `protobuf:"varint,7,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	LoanId        int32                  `protobuf:"varint,8,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	IsPayable     bool                   `protobuf:"varint,9,opt,name=is_payable,json=isPayable,proto3" json:"is_payable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillDetailsResponse_Field) Reset() {
	*x = GetBillDetailsResponse_Field{}
	mi := &file_loans_getbilldetails_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillDetailsResponse_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillDetailsResponse_Field) ProtoMessage() {}

func (x *GetBillDetailsResponse_Field) ProtoReflect() protoreflect.Message {
	mi := &file_loans_getbilldetails_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillDetailsResponse_Field.ProtoReflect.Descriptor instead.
func (*GetBillDetailsResponse_Field) Descriptor() ([]byte, []int) {
	return file_loans_getbilldetails_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetBillDetailsResponse_Field) GetBillAmount() int32 {
	if x != nil {
		return x.BillAmount
	}
	return 0
}

func (x *GetBillDetailsResponse_Field) GetBillDate() string {
	if x != nil {
		return x.BillDate
	}
	return ""
}

func (x *GetBillDetailsResponse_Field) GetPrincipal() int32 {
	if x != nil {
		return x.Principal
	}
	return 0
}

func (x *GetBillDetailsResponse_Field) GetInterest() int32 {
	if x != nil {
		return x.Interest
	}
	return 0
}

func (x *GetBillDetailsResponse_Field) GetInstId() int32 {
	if x != nil {
		return x.InstId
	}
	return 0
}

func (x *GetBillDetailsResponse_Field) GetPenalty() int32 {
	if x != nil {
		return x.Penalty
	}
	return 0
}

func (x *GetBillDetailsResponse_Field) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *GetBillDetailsResponse_Field) GetLoanId() int32 {
	if x != nil {
		return x.LoanId
	}
	return 0
}

func (x *GetBillDetailsResponse_Field) GetIsPayable() bool {
	if x != nil {
		return x.IsPayable
	}
	return false
}

var File_loans_getbilldetails_proto protoreflect.FileDescriptor

var file_loans_getbilldetails_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x6c, 0x6f, 0x61, 0x6e, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x62, 0x69, 0x6c, 0x6c, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6c, 0x6f,
	0x61, 0x6e, 0x73, 0x2e, 0x67, 0x65, 0x74, 0x62, 0x69, 0x6c, 0x6c, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x67, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xec, 0x02, 0x0a, 0x16,
	0x67, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x6c, 0x6f, 0x61, 0x6e, 0x73, 0x2e, 0x67, 0x65, 0x74,
	0x62, 0x69, 0x6c, 0x6c, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x67, 0x65, 0x74, 0x42,
	0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x89,
	0x02, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x69, 0x6c, 0x6c,
	0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62,
	0x69, 0x6c, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x6c,
	0x6c, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69,
	0x6c, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69,
	0x70, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6e, 0x63,
	0x69, 0x70, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x6e, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x69, 0x6e, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x6e,
	0x61, 0x6c, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x61,
	0x6c, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x56, 0x69, 0x73, 0x69, 0x62,
	0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x6f, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x73, 0x5f, 0x70, 0x61, 0x79, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x73, 0x50, 0x61, 0x79, 0x61, 0x62, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_loans_getbilldetails_proto_rawDescOnce sync.Once
	file_loans_getbilldetails_proto_rawDescData []byte
)

func file_loans_getbilldetails_proto_rawDescGZIP() []byte {
	file_loans_getbilldetails_proto_rawDescOnce.Do(func() {
		file_loans_getbilldetails_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loans_getbilldetails_proto_rawDesc), len(file_loans_getbilldetails_proto_rawDesc)))
	})
	return file_loans_getbilldetails_proto_rawDescData
}

var file_loans_getbilldetails_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_loans_getbilldetails_proto_goTypes = []any{
	(*GetBillDetailsRequest)(nil),        // 0: loans.getbilldetails.getBillDetailsRequest
	(*GetBillDetailsResponse)(nil),       // 1: loans.getbilldetails.getBillDetailsResponse
	(*GetBillDetailsResponse_Field)(nil), // 2: loans.getbilldetails.getBillDetailsResponse.Field
}
var file_loans_getbilldetails_proto_depIdxs = []int32{
	2, // 0: loans.getbilldetails.getBillDetailsResponse.data:type_name -> loans.getbilldetails.getBillDetailsResponse.Field
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_loans_getbilldetails_proto_init() }
func file_loans_getbilldetails_proto_init() {
	if File_loans_getbilldetails_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loans_getbilldetails_proto_rawDesc), len(file_loans_getbilldetails_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_loans_getbilldetails_proto_goTypes,
		DependencyIndexes: file_loans_getbilldetails_proto_depIdxs,
		MessageInfos:      file_loans_getbilldetails_proto_msgTypes,
	}.Build()
	File_loans_getbilldetails_proto = out.File
	file_loans_getbilldetails_proto_goTypes = nil
	file_loans_getbilldetails_proto_depIdxs = nil
}
