// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.6
// source: loans/getloctenure.proto

package loans

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLocTenureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GetLocTenureRequest) Reset() {
	*x = GetLocTenureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loans_getloctenure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocTenureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocTenureRequest) ProtoMessage() {}

func (x *GetLocTenureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loans_getloctenure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocTenureRequest.ProtoReflect.Descriptor instead.
func (*GetLocTenureRequest) Descriptor() ([]byte, []int) {
	return file_loans_getloctenure_proto_rawDescGZIP(), []int{0}
}

func (x *GetLocTenureRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TenureDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenure            int32   `protobuf:"varint,1,opt,name=tenure,proto3" json:"tenure,omitempty"`
	ExpectedEmiAmount float64 `protobuf:"fixed64,2,opt,name=expected_emi_amount,json=expectedEmiAmount,proto3" json:"expected_emi_amount,omitempty"`
}

func (x *TenureDetail) Reset() {
	*x = TenureDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loans_getloctenure_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenureDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenureDetail) ProtoMessage() {}

func (x *TenureDetail) ProtoReflect() protoreflect.Message {
	mi := &file_loans_getloctenure_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenureDetail.ProtoReflect.Descriptor instead.
func (*TenureDetail) Descriptor() ([]byte, []int) {
	return file_loans_getloctenure_proto_rawDescGZIP(), []int{1}
}

func (x *TenureDetail) GetTenure() int32 {
	if x != nil {
		return x.Tenure
	}
	return 0
}

func (x *TenureDetail) GetExpectedEmiAmount() float64 {
	if x != nil {
		return x.ExpectedEmiAmount
	}
	return 0
}

type GetLocTenureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount        int32           `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	BillDate      string          `protobuf:"bytes,2,opt,name=bill_date,json=billDate,proto3" json:"bill_date,omitempty"`
	MinTenure     int32           `protobuf:"varint,3,opt,name=min_tenure,json=minTenure,proto3" json:"min_tenure,omitempty"`
	MaxTenure     int32           `protobuf:"varint,4,opt,name=max_tenure,json=maxTenure,proto3" json:"max_tenure,omitempty"`
	Msg           *string         `protobuf:"bytes,5,opt,name=msg,proto3,oneof" json:"msg,omitempty"`
	FirstEmiDate  string          `protobuf:"bytes,6,opt,name=first_emi_date,json=firstEmiDate,proto3" json:"first_emi_date,omitempty"`
	FcpFee        string          `protobuf:"bytes,7,opt,name=fcp_fee,json=fcpFee,proto3" json:"fcp_fee,omitempty"`
	FcpInterest   int32           `protobuf:"varint,8,opt,name=fcp_interest,json=fcpInterest,proto3" json:"fcp_interest,omitempty"`
	TenureDetails []*TenureDetail `protobuf:"bytes,9,rep,name=tenure_details,json=tenureDetails,proto3" json:"tenure_details,omitempty"`
	IsFip         bool            `protobuf:"varint,10,opt,name=is_fip,json=isFip,proto3" json:"is_fip,omitempty"`
	AmountGrossup int32           `protobuf:"varint,11,opt,name=amount_grossup,json=amountGrossup,proto3" json:"amount_grossup,omitempty"`
}

func (x *GetLocTenureResponse) Reset() {
	*x = GetLocTenureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loans_getloctenure_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocTenureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocTenureResponse) ProtoMessage() {}

func (x *GetLocTenureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loans_getloctenure_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocTenureResponse.ProtoReflect.Descriptor instead.
func (*GetLocTenureResponse) Descriptor() ([]byte, []int) {
	return file_loans_getloctenure_proto_rawDescGZIP(), []int{2}
}

func (x *GetLocTenureResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetLocTenureResponse) GetBillDate() string {
	if x != nil {
		return x.BillDate
	}
	return ""
}

func (x *GetLocTenureResponse) GetMinTenure() int32 {
	if x != nil {
		return x.MinTenure
	}
	return 0
}

func (x *GetLocTenureResponse) GetMaxTenure() int32 {
	if x != nil {
		return x.MaxTenure
	}
	return 0
}

func (x *GetLocTenureResponse) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

func (x *GetLocTenureResponse) GetFirstEmiDate() string {
	if x != nil {
		return x.FirstEmiDate
	}
	return ""
}

func (x *GetLocTenureResponse) GetFcpFee() string {
	if x != nil {
		return x.FcpFee
	}
	return ""
}

func (x *GetLocTenureResponse) GetFcpInterest() int32 {
	if x != nil {
		return x.FcpInterest
	}
	return 0
}

func (x *GetLocTenureResponse) GetTenureDetails() []*TenureDetail {
	if x != nil {
		return x.TenureDetails
	}
	return nil
}

func (x *GetLocTenureResponse) GetIsFip() bool {
	if x != nil {
		return x.IsFip
	}
	return false
}

func (x *GetLocTenureResponse) GetAmountGrossup() int32 {
	if x != nil {
		return x.AmountGrossup
	}
	return 0
}

var File_loans_getloctenure_proto protoreflect.FileDescriptor

var file_loans_getloctenure_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6c, 0x6f, 0x61, 0x6e, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x6c, 0x6f, 0x63, 0x74, 0x65,
	0x6e, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6c, 0x6f, 0x61, 0x6e,
	0x73, 0x2e, 0x67, 0x65, 0x74, 0x6c, 0x6f, 0x63, 0x74, 0x65, 0x6e, 0x75, 0x72, 0x65, 0x22, 0x2d,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x54, 0x65, 0x6e, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x56, 0x0a,
	0x0c, 0x54, 0x65, 0x6e, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x65, 0x6e, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74,
	0x65, 0x6e, 0x75, 0x72, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x5f, 0x65, 0x6d, 0x69, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x11, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x45, 0x6d, 0x69, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x91, 0x03, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63,
	0x54, 0x65, 0x6e, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x6c, 0x6c, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x6c, 0x6c, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x5f, 0x74, 0x65, 0x6e, 0x75, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x54, 0x65, 0x6e, 0x75,
	0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x65, 0x6e, 0x75, 0x72, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x54, 0x65, 0x6e, 0x75, 0x72,
	0x65, 0x12, 0x15, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x5f, 0x65, 0x6d, 0x69, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x66, 0x69, 0x72, 0x73, 0x74, 0x45, 0x6d, 0x69, 0x44, 0x61, 0x74, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x66, 0x63, 0x70, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x66, 0x63, 0x70, 0x46, 0x65, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x63, 0x70, 0x5f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x66,
	0x63, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x0e, 0x74, 0x65,
	0x6e, 0x75, 0x72, 0x65, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x09, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6c, 0x6f, 0x61, 0x6e, 0x73, 0x2e, 0x67, 0x65, 0x74, 0x6c, 0x6f,
	0x63, 0x74, 0x65, 0x6e, 0x75, 0x72, 0x65, 0x2e, 0x54, 0x65, 0x6e, 0x75, 0x72, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x0d, 0x74, 0x65, 0x6e, 0x75, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x70, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x46, 0x69, 0x70, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x67, 0x72, 0x6f, 0x73, 0x73, 0x75, 0x70, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x72, 0x6f, 0x73, 0x73, 0x75,
	0x70, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_loans_getloctenure_proto_rawDescOnce sync.Once
	file_loans_getloctenure_proto_rawDescData = file_loans_getloctenure_proto_rawDesc
)

func file_loans_getloctenure_proto_rawDescGZIP() []byte {
	file_loans_getloctenure_proto_rawDescOnce.Do(func() {
		file_loans_getloctenure_proto_rawDescData = protoimpl.X.CompressGZIP(file_loans_getloctenure_proto_rawDescData)
	})
	return file_loans_getloctenure_proto_rawDescData
}

var file_loans_getloctenure_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_loans_getloctenure_proto_goTypes = []interface{}{
	(*GetLocTenureRequest)(nil),  // 0: loans.getloctenure.GetLocTenureRequest
	(*TenureDetail)(nil),         // 1: loans.getloctenure.TenureDetail
	(*GetLocTenureResponse)(nil), // 2: loans.getloctenure.GetLocTenureResponse
}
var file_loans_getloctenure_proto_depIdxs = []int32{
	1, // 0: loans.getloctenure.GetLocTenureResponse.tenure_details:type_name -> loans.getloctenure.TenureDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_loans_getloctenure_proto_init() }
func file_loans_getloctenure_proto_init() {
	if File_loans_getloctenure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_loans_getloctenure_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocTenureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loans_getloctenure_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenureDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loans_getloctenure_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocTenureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_loans_getloctenure_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_loans_getloctenure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_loans_getloctenure_proto_goTypes,
		DependencyIndexes: file_loans_getloctenure_proto_depIdxs,
		MessageInfos:      file_loans_getloctenure_proto_msgTypes,
	}.Build()
	File_loans_getloctenure_proto = out.File
	file_loans_getloctenure_proto_rawDesc = nil
	file_loans_getloctenure_proto_goTypes = nil
	file_loans_getloctenure_proto_depIdxs = nil
}
