// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.6
// source: loans/getpaymentoptions.proto

package loans

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPaymentOptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GetPaymentOptionsRequest) Reset() {
	*x = GetPaymentOptionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loans_getpaymentoptions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPaymentOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentOptionsRequest) ProtoMessage() {}

func (x *GetPaymentOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loans_getpaymentoptions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentOptionsRequest) Descriptor() ([]byte, []int) {
	return file_loans_getpaymentoptions_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaymentOptionsRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetPaymentOptionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options []*PaymentOptions `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *GetPaymentOptionsResponse) Reset() {
	*x = GetPaymentOptionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loans_getpaymentoptions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPaymentOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentOptionsResponse) ProtoMessage() {}

func (x *GetPaymentOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loans_getpaymentoptions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentOptionsResponse) Descriptor() ([]byte, []int) {
	return file_loans_getpaymentoptions_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentOptionsResponse) GetOptions() []*PaymentOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type PaymentOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modes       []string `protobuf:"bytes,1,rep,name=modes,proto3" json:"modes,omitempty"`
	Gateway     string   `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Amount      float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ServiceFee  float64  `protobuf:"fixed64,4,opt,name=service_fee,json=serviceFee,proto3" json:"service_fee,omitempty"`
	OtherFees   float64  `protobuf:"fixed64,5,opt,name=other_fees,json=otherFees,proto3" json:"other_fees,omitempty"`
	TotalAmount float64  `protobuf:"fixed64,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
}

func (x *PaymentOptions) Reset() {
	*x = PaymentOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loans_getpaymentoptions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentOptions) ProtoMessage() {}

func (x *PaymentOptions) ProtoReflect() protoreflect.Message {
	mi := &file_loans_getpaymentoptions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentOptions.ProtoReflect.Descriptor instead.
func (*PaymentOptions) Descriptor() ([]byte, []int) {
	return file_loans_getpaymentoptions_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentOptions) GetModes() []string {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *PaymentOptions) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *PaymentOptions) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentOptions) GetServiceFee() float64 {
	if x != nil {
		return x.ServiceFee
	}
	return 0
}

func (x *PaymentOptions) GetOtherFees() float64 {
	if x != nil {
		return x.OtherFees
	}
	return 0
}

func (x *PaymentOptions) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

var File_loans_getpaymentoptions_proto protoreflect.FileDescriptor

var file_loans_getpaymentoptions_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6c, 0x6f, 0x61, 0x6e, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x6c, 0x6f, 0x61, 0x6e, 0x73, 0x2e, 0x67, 0x65, 0x74, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x32, 0x0a, 0x18, 0x67, 0x65, 0x74, 0x50,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5e, 0x0a, 0x19,
	0x67, 0x65, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6c, 0x6f, 0x61,
	0x6e, 0x73, 0x2e, 0x67, 0x65, 0x74, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xbb, 0x01, 0x0a,
	0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x65, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x74, 0x68, 0x65,
	0x72, 0x5f, 0x66, 0x65, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x46, 0x65, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_loans_getpaymentoptions_proto_rawDescOnce sync.Once
	file_loans_getpaymentoptions_proto_rawDescData = file_loans_getpaymentoptions_proto_rawDesc
)

func file_loans_getpaymentoptions_proto_rawDescGZIP() []byte {
	file_loans_getpaymentoptions_proto_rawDescOnce.Do(func() {
		file_loans_getpaymentoptions_proto_rawDescData = protoimpl.X.CompressGZIP(file_loans_getpaymentoptions_proto_rawDescData)
	})
	return file_loans_getpaymentoptions_proto_rawDescData
}

var file_loans_getpaymentoptions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_loans_getpaymentoptions_proto_goTypes = []interface{}{
	(*GetPaymentOptionsRequest)(nil),  // 0: loans.getpaymentoptions.getPaymentOptionsRequest
	(*GetPaymentOptionsResponse)(nil), // 1: loans.getpaymentoptions.getPaymentOptionsResponse
	(*PaymentOptions)(nil),            // 2: loans.getpaymentoptions.paymentOptions
}
var file_loans_getpaymentoptions_proto_depIdxs = []int32{
	2, // 0: loans.getpaymentoptions.getPaymentOptionsResponse.options:type_name -> loans.getpaymentoptions.paymentOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_loans_getpaymentoptions_proto_init() }
func file_loans_getpaymentoptions_proto_init() {
	if File_loans_getpaymentoptions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_loans_getpaymentoptions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPaymentOptionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loans_getpaymentoptions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPaymentOptionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loans_getpaymentoptions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_loans_getpaymentoptions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_loans_getpaymentoptions_proto_goTypes,
		DependencyIndexes: file_loans_getpaymentoptions_proto_depIdxs,
		MessageInfos:      file_loans_getpaymentoptions_proto_msgTypes,
	}.Build()
	File_loans_getpaymentoptions_proto = out.File
	file_loans_getpaymentoptions_proto_rawDesc = nil
	file_loans_getpaymentoptions_proto_goTypes = nil
	file_loans_getpaymentoptions_proto_depIdxs = nil
}
