// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.6
// source: loans/paymentallocation.proto

package loans

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentAllocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentId  int32  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount     int32  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Mode       string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Customerid int32  `protobuf:"varint,4,opt,name=customerid,proto3" json:"customerid,omitempty"`
}

func (x *PaymentAllocationRequest) Reset() {
	*x = PaymentAllocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loans_paymentallocation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentAllocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAllocationRequest) ProtoMessage() {}

func (x *PaymentAllocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loans_paymentallocation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAllocationRequest.ProtoReflect.Descriptor instead.
func (*PaymentAllocationRequest) Descriptor() ([]byte, []int) {
	return file_loans_paymentallocation_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentAllocationRequest) GetPaymentId() int32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *PaymentAllocationRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentAllocationRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *PaymentAllocationRequest) GetCustomerid() int32 {
	if x != nil {
		return x.Customerid
	}
	return 0
}

type PaymentAllocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PaymentAllocationResponse) Reset() {
	*x = PaymentAllocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loans_paymentallocation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentAllocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAllocationResponse) ProtoMessage() {}

func (x *PaymentAllocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loans_paymentallocation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAllocationResponse.ProtoReflect.Descriptor instead.
func (*PaymentAllocationResponse) Descriptor() ([]byte, []int) {
	return file_loans_paymentallocation_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentAllocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_loans_paymentallocation_proto protoreflect.FileDescriptor

var file_loans_paymentallocation_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6c, 0x6f, 0x61, 0x6e, 0x73, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x6c, 0x6f, 0x61, 0x6e, 0x73, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x85, 0x01, 0x0a, 0x18, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x69, 0x64,
	0x22, 0x35, 0x0a, 0x19, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_loans_paymentallocation_proto_rawDescOnce sync.Once
	file_loans_paymentallocation_proto_rawDescData = file_loans_paymentallocation_proto_rawDesc
)

func file_loans_paymentallocation_proto_rawDescGZIP() []byte {
	file_loans_paymentallocation_proto_rawDescOnce.Do(func() {
		file_loans_paymentallocation_proto_rawDescData = protoimpl.X.CompressGZIP(file_loans_paymentallocation_proto_rawDescData)
	})
	return file_loans_paymentallocation_proto_rawDescData
}

var file_loans_paymentallocation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_loans_paymentallocation_proto_goTypes = []interface{}{
	(*PaymentAllocationRequest)(nil),  // 0: loans.paymentallocation.paymentAllocationRequest
	(*PaymentAllocationResponse)(nil), // 1: loans.paymentallocation.paymentAllocationResponse
}
var file_loans_paymentallocation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_loans_paymentallocation_proto_init() }
func file_loans_paymentallocation_proto_init() {
	if File_loans_paymentallocation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_loans_paymentallocation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentAllocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loans_paymentallocation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentAllocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_loans_paymentallocation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_loans_paymentallocation_proto_goTypes,
		DependencyIndexes: file_loans_paymentallocation_proto_depIdxs,
		MessageInfos:      file_loans_paymentallocation_proto_msgTypes,
	}.Build()
	File_loans_paymentallocation_proto = out.File
	file_loans_paymentallocation_proto_rawDesc = nil
	file_loans_paymentallocation_proto_goTypes = nil
	file_loans_paymentallocation_proto_depIdxs = nil
}
