// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: payments.proto

package stashfin_com

import (
	context "context"
	payments "github.com/stashfin2/grpc/stashfin.com/payments"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Payments_Getpaymentoptions_FullMethodName  = "/service.payments/getpaymentoptions"
	Payments_Initiatepayment_FullMethodName    = "/service.payments/initiatepayment"
	Payments_Checkpaymentstatus_FullMethodName = "/service.payments/checkpaymentstatus"
	Payments_Nachregistration_FullMethodName   = "/service.payments/nachregistration"
	Payments_Nachpresentation_FullMethodName   = "/service.payments/nachpresentation"
	Payments_Fundtransfer_FullMethodName       = "/service.payments/fundtransfer"
)

// PaymentsClient is the client API for Payments service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentsClient interface {
	Getpaymentoptions(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error)
	Initiatepayment(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error)
	Checkpaymentstatus(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error)
	Nachregistration(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error)
	Nachpresentation(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error)
	Fundtransfer(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error)
}

type paymentsClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentsClient(cc grpc.ClientConnInterface) PaymentsClient {
	return &paymentsClient{cc}
}

func (c *paymentsClient) Getpaymentoptions(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error) {
	out := new(payments.Response)
	err := c.cc.Invoke(ctx, Payments_Getpaymentoptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) Initiatepayment(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error) {
	out := new(payments.Response)
	err := c.cc.Invoke(ctx, Payments_Initiatepayment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) Checkpaymentstatus(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error) {
	out := new(payments.Response)
	err := c.cc.Invoke(ctx, Payments_Checkpaymentstatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) Nachregistration(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error) {
	out := new(payments.Response)
	err := c.cc.Invoke(ctx, Payments_Nachregistration_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) Nachpresentation(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error) {
	out := new(payments.Response)
	err := c.cc.Invoke(ctx, Payments_Nachpresentation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsClient) Fundtransfer(ctx context.Context, in *payments.Request, opts ...grpc.CallOption) (*payments.Response, error) {
	out := new(payments.Response)
	err := c.cc.Invoke(ctx, Payments_Fundtransfer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentsServer is the server API for Payments service.
// All implementations must embed UnimplementedPaymentsServer
// for forward compatibility
type PaymentsServer interface {
	Getpaymentoptions(context.Context, *payments.Request) (*payments.Response, error)
	Initiatepayment(context.Context, *payments.Request) (*payments.Response, error)
	Checkpaymentstatus(context.Context, *payments.Request) (*payments.Response, error)
	Nachregistration(context.Context, *payments.Request) (*payments.Response, error)
	Nachpresentation(context.Context, *payments.Request) (*payments.Response, error)
	Fundtransfer(context.Context, *payments.Request) (*payments.Response, error)
	mustEmbedUnimplementedPaymentsServer()
}

// UnimplementedPaymentsServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentsServer struct {
}

func (UnimplementedPaymentsServer) Getpaymentoptions(context.Context, *payments.Request) (*payments.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Getpaymentoptions not implemented")
}
func (UnimplementedPaymentsServer) Initiatepayment(context.Context, *payments.Request) (*payments.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initiatepayment not implemented")
}
func (UnimplementedPaymentsServer) Checkpaymentstatus(context.Context, *payments.Request) (*payments.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkpaymentstatus not implemented")
}
func (UnimplementedPaymentsServer) Nachregistration(context.Context, *payments.Request) (*payments.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Nachregistration not implemented")
}
func (UnimplementedPaymentsServer) Nachpresentation(context.Context, *payments.Request) (*payments.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Nachpresentation not implemented")
}
func (UnimplementedPaymentsServer) Fundtransfer(context.Context, *payments.Request) (*payments.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fundtransfer not implemented")
}
func (UnimplementedPaymentsServer) mustEmbedUnimplementedPaymentsServer() {}

// UnsafePaymentsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentsServer will
// result in compilation errors.
type UnsafePaymentsServer interface {
	mustEmbedUnimplementedPaymentsServer()
}

func RegisterPaymentsServer(s grpc.ServiceRegistrar, srv PaymentsServer) {
	s.RegisterService(&Payments_ServiceDesc, srv)
}

func _Payments_Getpaymentoptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payments.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).Getpaymentoptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payments_Getpaymentoptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).Getpaymentoptions(ctx, req.(*payments.Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_Initiatepayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payments.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).Initiatepayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payments_Initiatepayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).Initiatepayment(ctx, req.(*payments.Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_Checkpaymentstatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payments.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).Checkpaymentstatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payments_Checkpaymentstatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).Checkpaymentstatus(ctx, req.(*payments.Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_Nachregistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payments.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).Nachregistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payments_Nachregistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).Nachregistration(ctx, req.(*payments.Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_Nachpresentation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payments.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).Nachpresentation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payments_Nachpresentation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).Nachpresentation(ctx, req.(*payments.Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payments_Fundtransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payments.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServer).Fundtransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payments_Fundtransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServer).Fundtransfer(ctx, req.(*payments.Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Payments_ServiceDesc is the grpc.ServiceDesc for Payments service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payments_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.payments",
	HandlerType: (*PaymentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getpaymentoptions",
			Handler:    _Payments_Getpaymentoptions_Handler,
		},
		{
			MethodName: "initiatepayment",
			Handler:    _Payments_Initiatepayment_Handler,
		},
		{
			MethodName: "checkpaymentstatus",
			Handler:    _Payments_Checkpaymentstatus_Handler,
		},
		{
			MethodName: "nachregistration",
			Handler:    _Payments_Nachregistration_Handler,
		},
		{
			MethodName: "nachpresentation",
			Handler:    _Payments_Nachpresentation_Handler,
		},
		{
			MethodName: "fundtransfer",
			Handler:    _Payments_Fundtransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments.proto",
}
