// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.6
// source: customers/floatingvideos.proto

package customers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFloatingVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFloatingVideosRequest) Reset() {
	*x = GetFloatingVideosRequest{}
	mi := &file_customers_floatingvideos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFloatingVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFloatingVideosRequest) ProtoMessage() {}

func (x *GetFloatingVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customers_floatingvideos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFloatingVideosRequest.ProtoReflect.Descriptor instead.
func (*GetFloatingVideosRequest) Descriptor() ([]byte, []int) {
	return file_customers_floatingvideos_proto_rawDescGZIP(), []int{0}
}

type FloatingVideo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageCode      string                 `protobuf:"bytes,1,opt,name=page_code,json=pageCode,proto3" json:"page_code,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatingVideo) Reset() {
	*x = FloatingVideo{}
	mi := &file_customers_floatingvideos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatingVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatingVideo) ProtoMessage() {}

func (x *FloatingVideo) ProtoReflect() protoreflect.Message {
	mi := &file_customers_floatingvideos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatingVideo.ProtoReflect.Descriptor instead.
func (*FloatingVideo) Descriptor() ([]byte, []int) {
	return file_customers_floatingvideos_proto_rawDescGZIP(), []int{1}
}

func (x *FloatingVideo) GetPageCode() string {
	if x != nil {
		return x.PageCode
	}
	return ""
}

func (x *FloatingVideo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetFloatingVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*FloatingVideo       `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFloatingVideosResponse) Reset() {
	*x = GetFloatingVideosResponse{}
	mi := &file_customers_floatingvideos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFloatingVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFloatingVideosResponse) ProtoMessage() {}

func (x *GetFloatingVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customers_floatingvideos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFloatingVideosResponse.ProtoReflect.Descriptor instead.
func (*GetFloatingVideosResponse) Descriptor() ([]byte, []int) {
	return file_customers_floatingvideos_proto_rawDescGZIP(), []int{2}
}

func (x *GetFloatingVideosResponse) GetVideos() []*FloatingVideo {
	if x != nil {
		return x.Videos
	}
	return nil
}

var File_customers_floatingvideos_proto protoreflect.FileDescriptor

var file_customers_floatingvideos_proto_rawDesc = string([]byte{
	0x0a, 0x1e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2f, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x18, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x67, 0x65,
	0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x0d, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x5c, 0x0a, 0x19, 0x67, 0x65, 0x74, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2e,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x2e, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x06, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_customers_floatingvideos_proto_rawDescOnce sync.Once
	file_customers_floatingvideos_proto_rawDescData []byte
)

func file_customers_floatingvideos_proto_rawDescGZIP() []byte {
	file_customers_floatingvideos_proto_rawDescOnce.Do(func() {
		file_customers_floatingvideos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customers_floatingvideos_proto_rawDesc), len(file_customers_floatingvideos_proto_rawDesc)))
	})
	return file_customers_floatingvideos_proto_rawDescData
}

var file_customers_floatingvideos_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_customers_floatingvideos_proto_goTypes = []any{
	(*GetFloatingVideosRequest)(nil),  // 0: customers.floatingvideos.getFloatingVideosRequest
	(*FloatingVideo)(nil),             // 1: customers.floatingvideos.FloatingVideo
	(*GetFloatingVideosResponse)(nil), // 2: customers.floatingvideos.getFloatingVideosResponse
}
var file_customers_floatingvideos_proto_depIdxs = []int32{
	1, // 0: customers.floatingvideos.getFloatingVideosResponse.videos:type_name -> customers.floatingvideos.FloatingVideo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_customers_floatingvideos_proto_init() }
func file_customers_floatingvideos_proto_init() {
	if File_customers_floatingvideos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customers_floatingvideos_proto_rawDesc), len(file_customers_floatingvideos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customers_floatingvideos_proto_goTypes,
		DependencyIndexes: file_customers_floatingvideos_proto_depIdxs,
		MessageInfos:      file_customers_floatingvideos_proto_msgTypes,
	}.Build()
	File_customers_floatingvideos_proto = out.File
	file_customers_floatingvideos_proto_goTypes = nil
	file_customers_floatingvideos_proto_depIdxs = nil
}
