// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.6
// source: customers/getprofessionalinfo.proto

package customers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfessionalInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfessionalInfoRequest) Reset() {
	*x = GetProfessionalInfoRequest{}
	mi := &file_customers_getprofessionalinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfessionalInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfessionalInfoRequest) ProtoMessage() {}

func (x *GetProfessionalInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customers_getprofessionalinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfessionalInfoRequest.ProtoReflect.Descriptor instead.
func (*GetProfessionalInfoRequest) Descriptor() ([]byte, []int) {
	return file_customers_getprofessionalinfo_proto_rawDescGZIP(), []int{0}
}

type GetProfessionalInfoResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	CompanyName   string                   `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Designation   string                   `protobuf:"bytes,2,opt,name=designation,proto3" json:"designation,omitempty"`
	OfficialEmail string                   `protobuf:"bytes,3,opt,name=official_email,json=officialEmail,proto3" json:"official_email,omitempty"`
	OfficeAddr    *ProfessionalInfoAddress `protobuf:"bytes,4,opt,name=office_addr,json=officeAddr,proto3" json:"office_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfessionalInfoResponse) Reset() {
	*x = GetProfessionalInfoResponse{}
	mi := &file_customers_getprofessionalinfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfessionalInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfessionalInfoResponse) ProtoMessage() {}

func (x *GetProfessionalInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customers_getprofessionalinfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfessionalInfoResponse.ProtoReflect.Descriptor instead.
func (*GetProfessionalInfoResponse) Descriptor() ([]byte, []int) {
	return file_customers_getprofessionalinfo_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfessionalInfoResponse) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *GetProfessionalInfoResponse) GetDesignation() string {
	if x != nil {
		return x.Designation
	}
	return ""
}

func (x *GetProfessionalInfoResponse) GetOfficialEmail() string {
	if x != nil {
		return x.OfficialEmail
	}
	return ""
}

func (x *GetProfessionalInfoResponse) GetOfficeAddr() *ProfessionalInfoAddress {
	if x != nil {
		return x.OfficeAddr
	}
	return nil
}

type ProfessionalInfoAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseFlatNo   string                 `protobuf:"bytes,1,opt,name=house_flat_no,json=houseFlatNo,proto3" json:"house_flat_no,omitempty"`
	AddressLine_1 string                 `protobuf:"bytes,2,opt,name=address_line_1,json=addressLine1,proto3" json:"address_line_1,omitempty"`
	AddressLine_2 string                 `protobuf:"bytes,3,opt,name=address_line_2,json=addressLine2,proto3" json:"address_line_2,omitempty"`
	Landmark      string                 `protobuf:"bytes,4,opt,name=landmark,proto3" json:"landmark,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	PinCode       string                 `protobuf:"bytes,7,opt,name=pin_code,json=pinCode,proto3" json:"pin_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfessionalInfoAddress) Reset() {
	*x = ProfessionalInfoAddress{}
	mi := &file_customers_getprofessionalinfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfessionalInfoAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfessionalInfoAddress) ProtoMessage() {}

func (x *ProfessionalInfoAddress) ProtoReflect() protoreflect.Message {
	mi := &file_customers_getprofessionalinfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfessionalInfoAddress.ProtoReflect.Descriptor instead.
func (*ProfessionalInfoAddress) Descriptor() ([]byte, []int) {
	return file_customers_getprofessionalinfo_proto_rawDescGZIP(), []int{2}
}

func (x *ProfessionalInfoAddress) GetHouseFlatNo() string {
	if x != nil {
		return x.HouseFlatNo
	}
	return ""
}

func (x *ProfessionalInfoAddress) GetAddressLine_1() string {
	if x != nil {
		return x.AddressLine_1
	}
	return ""
}

func (x *ProfessionalInfoAddress) GetAddressLine_2() string {
	if x != nil {
		return x.AddressLine_2
	}
	return ""
}

func (x *ProfessionalInfoAddress) GetLandmark() string {
	if x != nil {
		return x.Landmark
	}
	return ""
}

func (x *ProfessionalInfoAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ProfessionalInfoAddress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProfessionalInfoAddress) GetPinCode() string {
	if x != nil {
		return x.PinCode
	}
	return ""
}

var File_customers_getprofessionalinfo_proto protoreflect.FileDescriptor

var file_customers_getprofessionalinfo_proto_rawDesc = string([]byte{
	0x0a, 0x23, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x70,
	0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73,
	0x2e, 0x67, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x69, 0x6e, 0x66, 0x6f, 0x22, 0x1c, 0x0a, 0x1a, 0x67, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xe2, 0x01, 0x0a, 0x1b, 0x67, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x66, 0x66, 0x69, 0x63,
	0x69, 0x61, 0x6c, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x57,
	0x0a, 0x0b, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2e,
	0x67, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0a, 0x6f, 0x66, 0x66,
	0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x22, 0xea, 0x01, 0x0a, 0x17, 0x70, 0x72, 0x6f, 0x66,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x66, 0x6c, 0x61,
	0x74, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x46, 0x6c, 0x61, 0x74, 0x4e, 0x6f, 0x12, 0x24, 0x0a, 0x0e, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x6e, 0x65, 0x31, 0x12, 0x24, 0x0a,
	0x0e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x32, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69,
	0x6e, 0x65, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x64, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x64, 0x6d, 0x61, 0x72, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x69, 0x6e,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x69, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_customers_getprofessionalinfo_proto_rawDescOnce sync.Once
	file_customers_getprofessionalinfo_proto_rawDescData []byte
)

func file_customers_getprofessionalinfo_proto_rawDescGZIP() []byte {
	file_customers_getprofessionalinfo_proto_rawDescOnce.Do(func() {
		file_customers_getprofessionalinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customers_getprofessionalinfo_proto_rawDesc), len(file_customers_getprofessionalinfo_proto_rawDesc)))
	})
	return file_customers_getprofessionalinfo_proto_rawDescData
}

var file_customers_getprofessionalinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_customers_getprofessionalinfo_proto_goTypes = []any{
	(*GetProfessionalInfoRequest)(nil),  // 0: customers.getprofessionalinfo.getProfessionalInfoRequest
	(*GetProfessionalInfoResponse)(nil), // 1: customers.getprofessionalinfo.getProfessionalInfoResponse
	(*ProfessionalInfoAddress)(nil),     // 2: customers.getprofessionalinfo.professionalInfoAddress
}
var file_customers_getprofessionalinfo_proto_depIdxs = []int32{
	2, // 0: customers.getprofessionalinfo.getProfessionalInfoResponse.office_addr:type_name -> customers.getprofessionalinfo.professionalInfoAddress
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_customers_getprofessionalinfo_proto_init() }
func file_customers_getprofessionalinfo_proto_init() {
	if File_customers_getprofessionalinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customers_getprofessionalinfo_proto_rawDesc), len(file_customers_getprofessionalinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customers_getprofessionalinfo_proto_goTypes,
		DependencyIndexes: file_customers_getprofessionalinfo_proto_depIdxs,
		MessageInfos:      file_customers_getprofessionalinfo_proto_msgTypes,
	}.Build()
	File_customers_getprofessionalinfo_proto = out.File
	file_customers_getprofessionalinfo_proto_goTypes = nil
	file_customers_getprofessionalinfo_proto_depIdxs = nil
}
