// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.6
// source: customers/getsyncstatus.proto

package customers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSyncStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSyncStatusRequest) Reset() {
	*x = GetSyncStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_getsyncstatus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSyncStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncStatusRequest) ProtoMessage() {}

func (x *GetSyncStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customers_getsyncstatus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSyncStatusRequest) Descriptor() ([]byte, []int) {
	return file_customers_getsyncstatus_proto_rawDescGZIP(), []int{0}
}

type GetSyncStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmsSync bool `protobuf:"varint,1,opt,name=sms_sync,json=smsSync,proto3" json:"sms_sync,omitempty"`
	AppSync bool `protobuf:"varint,2,opt,name=app_sync,json=appSync,proto3" json:"app_sync,omitempty"`
}

func (x *GetSyncStatusResponse) Reset() {
	*x = GetSyncStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_getsyncstatus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSyncStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncStatusResponse) ProtoMessage() {}

func (x *GetSyncStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customers_getsyncstatus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSyncStatusResponse) Descriptor() ([]byte, []int) {
	return file_customers_getsyncstatus_proto_rawDescGZIP(), []int{1}
}

func (x *GetSyncStatusResponse) GetSmsSync() bool {
	if x != nil {
		return x.SmsSync
	}
	return false
}

func (x *GetSyncStatusResponse) GetAppSync() bool {
	if x != nil {
		return x.AppSync
	}
	return false
}

var File_customers_getsyncstatus_proto protoreflect.FileDescriptor

var file_customers_getsyncstatus_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x73,
	0x79, 0x6e, 0x63, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x67, 0x65, 0x74, 0x73, 0x79,
	0x6e, 0x63, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x53,
	0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x4d, 0x0a, 0x15, 0x67, 0x65, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6d, 0x73,
	0x5f, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x6d, 0x73,
	0x53, 0x79, 0x6e, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x79, 0x6e, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x70, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_customers_getsyncstatus_proto_rawDescOnce sync.Once
	file_customers_getsyncstatus_proto_rawDescData = file_customers_getsyncstatus_proto_rawDesc
)

func file_customers_getsyncstatus_proto_rawDescGZIP() []byte {
	file_customers_getsyncstatus_proto_rawDescOnce.Do(func() {
		file_customers_getsyncstatus_proto_rawDescData = protoimpl.X.CompressGZIP(file_customers_getsyncstatus_proto_rawDescData)
	})
	return file_customers_getsyncstatus_proto_rawDescData
}

var file_customers_getsyncstatus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_customers_getsyncstatus_proto_goTypes = []interface{}{
	(*GetSyncStatusRequest)(nil),  // 0: customers.getsyncstatus.getSyncStatusRequest
	(*GetSyncStatusResponse)(nil), // 1: customers.getsyncstatus.getSyncStatusResponse
}
var file_customers_getsyncstatus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_customers_getsyncstatus_proto_init() }
func file_customers_getsyncstatus_proto_init() {
	if File_customers_getsyncstatus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_customers_getsyncstatus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSyncStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_getsyncstatus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSyncStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_customers_getsyncstatus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customers_getsyncstatus_proto_goTypes,
		DependencyIndexes: file_customers_getsyncstatus_proto_depIdxs,
		MessageInfos:      file_customers_getsyncstatus_proto_msgTypes,
	}.Build()
	File_customers_getsyncstatus_proto = out.File
	file_customers_getsyncstatus_proto_rawDesc = nil
	file_customers_getsyncstatus_proto_goTypes = nil
	file_customers_getsyncstatus_proto_depIdxs = nil
}
