// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.6
// source: customers/setmpin.proto

package customers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetMpinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Mpin   int32  `protobuf:"varint,2,opt,name=mpin,proto3" json:"mpin,omitempty"`
}

func (x *SetMpinRequest) Reset() {
	*x = SetMpinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_setmpin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMpinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMpinRequest) ProtoMessage() {}

func (x *SetMpinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customers_setmpin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMpinRequest.ProtoReflect.Descriptor instead.
func (*SetMpinRequest) Descriptor() ([]byte, []int) {
	return file_customers_setmpin_proto_rawDescGZIP(), []int{0}
}

func (x *SetMpinRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SetMpinRequest) GetMpin() int32 {
	if x != nil {
		return x.Mpin
	}
	return 0
}

type SetMpinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SetMpinResponse) Reset() {
	*x = SetMpinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_setmpin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMpinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMpinResponse) ProtoMessage() {}

func (x *SetMpinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customers_setmpin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMpinResponse.ProtoReflect.Descriptor instead.
func (*SetMpinResponse) Descriptor() ([]byte, []int) {
	return file_customers_setmpin_proto_rawDescGZIP(), []int{1}
}

func (x *SetMpinResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_customers_setmpin_proto protoreflect.FileDescriptor

var file_customers_setmpin_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2f, 0x73, 0x65, 0x74, 0x6d,
	0x70, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x65, 0x74, 0x6d, 0x70, 0x69, 0x6e, 0x22, 0x3c, 0x0a, 0x0e,
	0x73, 0x65, 0x74, 0x4d, 0x70, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x70, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x70, 0x69, 0x6e, 0x22, 0x29, 0x0a, 0x0f, 0x73, 0x65,
	0x74, 0x4d, 0x70, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_customers_setmpin_proto_rawDescOnce sync.Once
	file_customers_setmpin_proto_rawDescData = file_customers_setmpin_proto_rawDesc
)

func file_customers_setmpin_proto_rawDescGZIP() []byte {
	file_customers_setmpin_proto_rawDescOnce.Do(func() {
		file_customers_setmpin_proto_rawDescData = protoimpl.X.CompressGZIP(file_customers_setmpin_proto_rawDescData)
	})
	return file_customers_setmpin_proto_rawDescData
}

var file_customers_setmpin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_customers_setmpin_proto_goTypes = []interface{}{
	(*SetMpinRequest)(nil),  // 0: customers.setmpin.setMpinRequest
	(*SetMpinResponse)(nil), // 1: customers.setmpin.setMpinResponse
}
var file_customers_setmpin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_customers_setmpin_proto_init() }
func file_customers_setmpin_proto_init() {
	if File_customers_setmpin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_customers_setmpin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMpinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_setmpin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMpinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_customers_setmpin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customers_setmpin_proto_goTypes,
		DependencyIndexes: file_customers_setmpin_proto_depIdxs,
		MessageInfos:      file_customers_setmpin_proto_msgTypes,
	}.Build()
	File_customers_setmpin_proto = out.File
	file_customers_setmpin_proto_rawDesc = nil
	file_customers_setmpin_proto_goTypes = nil
	file_customers_setmpin_proto_depIdxs = nil
}
