// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.6
// source: customers/stepstatic.proto

package customers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StepstaticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepstaticRequest) Reset() {
	*x = StepstaticRequest{}
	mi := &file_customers_stepstatic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepstaticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepstaticRequest) ProtoMessage() {}

func (x *StepstaticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customers_stepstatic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepstaticRequest.ProtoReflect.Descriptor instead.
func (*StepstaticRequest) Descriptor() ([]byte, []int) {
	return file_customers_stepstatic_proto_rawDescGZIP(), []int{0}
}

type Validation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validation) Reset() {
	*x = Validation{}
	mi := &file_customers_stepstatic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validation) ProtoMessage() {}

func (x *Validation) ProtoReflect() protoreflect.Message {
	mi := &file_customers_stepstatic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validation.ProtoReflect.Descriptor instead.
func (*Validation) Descriptor() ([]byte, []int) {
	return file_customers_stepstatic_proto_rawDescGZIP(), []int{1}
}

func (x *Validation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Validation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Validation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StepstaticResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Page          string                      `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Type          string                      `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ButtonText    string                      `protobuf:"bytes,3,opt,name=button_text,json=buttonText,proto3" json:"button_text,omitempty"`
	Data          []*StepstaticResponse_Field `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepstaticResponse) Reset() {
	*x = StepstaticResponse{}
	mi := &file_customers_stepstatic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepstaticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepstaticResponse) ProtoMessage() {}

func (x *StepstaticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customers_stepstatic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepstaticResponse.ProtoReflect.Descriptor instead.
func (*StepstaticResponse) Descriptor() ([]byte, []int) {
	return file_customers_stepstatic_proto_rawDescGZIP(), []int{2}
}

func (x *StepstaticResponse) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *StepstaticResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StepstaticResponse) GetButtonText() string {
	if x != nil {
		return x.ButtonText
	}
	return ""
}

func (x *StepstaticResponse) GetData() []*StepstaticResponse_Field {
	if x != nil {
		return x.Data
	}
	return nil
}

type StepstaticResponse_Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	InputType     string                 `protobuf:"bytes,3,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	DataType      string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Validations   []*Validation          `protobuf:"bytes,7,rep,name=validations,proto3" json:"validations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepstaticResponse_Field) Reset() {
	*x = StepstaticResponse_Field{}
	mi := &file_customers_stepstatic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepstaticResponse_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepstaticResponse_Field) ProtoMessage() {}

func (x *StepstaticResponse_Field) ProtoReflect() protoreflect.Message {
	mi := &file_customers_stepstatic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepstaticResponse_Field.ProtoReflect.Descriptor instead.
func (*StepstaticResponse_Field) Descriptor() ([]byte, []int) {
	return file_customers_stepstatic_proto_rawDescGZIP(), []int{2, 0}
}

func (x *StepstaticResponse_Field) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *StepstaticResponse_Field) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StepstaticResponse_Field) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *StepstaticResponse_Field) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *StepstaticResponse_Field) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *StepstaticResponse_Field) GetValidations() []*Validation {
	if x != nil {
		return x.Validations
	}
	return nil
}

var File_customers_stepstatic_proto protoreflect.FileDescriptor

var file_customers_stepstatic_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2f, 0x73, 0x74, 0x65, 0x70,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x65, 0x70, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x63, 0x22, 0x13, 0x0a, 0x11, 0x73, 0x74, 0x65, 0x70, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x0a, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xe7, 0x02, 0x0a, 0x12, 0x73, 0x74, 0x65, 0x70,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e,
	0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x74,
	0x74, 0x6f, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x12, 0x42, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x73, 0x2e, 0x73, 0x74, 0x65, 0x70, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x2e, 0x73, 0x74, 0x65,
	0x70, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xc3, 0x01, 0x0a, 0x05,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x42, 0x0a,
	0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x73,
	0x74, 0x65, 0x70, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_customers_stepstatic_proto_rawDescOnce sync.Once
	file_customers_stepstatic_proto_rawDescData []byte
)

func file_customers_stepstatic_proto_rawDescGZIP() []byte {
	file_customers_stepstatic_proto_rawDescOnce.Do(func() {
		file_customers_stepstatic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customers_stepstatic_proto_rawDesc), len(file_customers_stepstatic_proto_rawDesc)))
	})
	return file_customers_stepstatic_proto_rawDescData
}

var file_customers_stepstatic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_customers_stepstatic_proto_goTypes = []any{
	(*StepstaticRequest)(nil),        // 0: customers.stepstatic.stepstaticRequest
	(*Validation)(nil),               // 1: customers.stepstatic.Validation
	(*StepstaticResponse)(nil),       // 2: customers.stepstatic.stepstaticResponse
	(*StepstaticResponse_Field)(nil), // 3: customers.stepstatic.stepstaticResponse.Field
}
var file_customers_stepstatic_proto_depIdxs = []int32{
	3, // 0: customers.stepstatic.stepstaticResponse.data:type_name -> customers.stepstatic.stepstaticResponse.Field
	1, // 1: customers.stepstatic.stepstaticResponse.Field.validations:type_name -> customers.stepstatic.Validation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_customers_stepstatic_proto_init() }
func file_customers_stepstatic_proto_init() {
	if File_customers_stepstatic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customers_stepstatic_proto_rawDesc), len(file_customers_stepstatic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customers_stepstatic_proto_goTypes,
		DependencyIndexes: file_customers_stepstatic_proto_depIdxs,
		MessageInfos:      file_customers_stepstatic_proto_msgTypes,
	}.Build()
	File_customers_stepstatic_proto = out.File
	file_customers_stepstatic_proto_goTypes = nil
	file_customers_stepstatic_proto_depIdxs = nil
}
