// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.6
// source: customers/enach/gettxnstatus.proto

package enach

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTxnStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxnStatusRequest) Reset() {
	*x = GetTxnStatusRequest{}
	mi := &file_customers_enach_gettxnstatus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxnStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxnStatusRequest) ProtoMessage() {}

func (x *GetTxnStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customers_enach_gettxnstatus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxnStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTxnStatusRequest) Descriptor() ([]byte, []int) {
	return file_customers_enach_gettxnstatus_proto_rawDescGZIP(), []int{0}
}

func (x *GetTxnStatusRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

type GetTxnStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxnStatusResponse) Reset() {
	*x = GetTxnStatusResponse{}
	mi := &file_customers_enach_gettxnstatus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxnStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxnStatusResponse) ProtoMessage() {}

func (x *GetTxnStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customers_enach_gettxnstatus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxnStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTxnStatusResponse) Descriptor() ([]byte, []int) {
	return file_customers_enach_gettxnstatus_proto_rawDescGZIP(), []int{1}
}

func (x *GetTxnStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_customers_enach_gettxnstatus_proto protoreflect.FileDescriptor

var file_customers_enach_gettxnstatus_proto_rawDesc = string([]byte{
	0x0a, 0x22, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2f, 0x65, 0x6e, 0x61, 0x63,
	0x68, 0x2f, 0x67, 0x65, 0x74, 0x74, 0x78, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2e,
	0x65, 0x6e, 0x61, 0x63, 0x68, 0x2e, 0x67, 0x65, 0x74, 0x74, 0x78, 0x6e, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x2c, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x78, 0x6e, 0x49, 0x64,
	0x22, 0x2e, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_customers_enach_gettxnstatus_proto_rawDescOnce sync.Once
	file_customers_enach_gettxnstatus_proto_rawDescData []byte
)

func file_customers_enach_gettxnstatus_proto_rawDescGZIP() []byte {
	file_customers_enach_gettxnstatus_proto_rawDescOnce.Do(func() {
		file_customers_enach_gettxnstatus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customers_enach_gettxnstatus_proto_rawDesc), len(file_customers_enach_gettxnstatus_proto_rawDesc)))
	})
	return file_customers_enach_gettxnstatus_proto_rawDescData
}

var file_customers_enach_gettxnstatus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_customers_enach_gettxnstatus_proto_goTypes = []any{
	(*GetTxnStatusRequest)(nil),  // 0: customers.enach.gettxnstatus.getTxnStatusRequest
	(*GetTxnStatusResponse)(nil), // 1: customers.enach.gettxnstatus.getTxnStatusResponse
}
var file_customers_enach_gettxnstatus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_customers_enach_gettxnstatus_proto_init() }
func file_customers_enach_gettxnstatus_proto_init() {
	if File_customers_enach_gettxnstatus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customers_enach_gettxnstatus_proto_rawDesc), len(file_customers_enach_gettxnstatus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customers_enach_gettxnstatus_proto_goTypes,
		DependencyIndexes: file_customers_enach_gettxnstatus_proto_depIdxs,
		MessageInfos:      file_customers_enach_gettxnstatus_proto_msgTypes,
	}.Build()
	File_customers_enach_gettxnstatus_proto = out.File
	file_customers_enach_gettxnstatus_proto_goTypes = nil
	file_customers_enach_gettxnstatus_proto_depIdxs = nil
}
