// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.6
// source: stashcash/getscbalance.proto

package stashcash

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetscbalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int64                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetscbalanceRequest) Reset() {
	*x = GetscbalanceRequest{}
	mi := &file_stashcash_getscbalance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetscbalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetscbalanceRequest) ProtoMessage() {}

func (x *GetscbalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stashcash_getscbalance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetscbalanceRequest.ProtoReflect.Descriptor instead.
func (*GetscbalanceRequest) Descriptor() ([]byte, []int) {
	return file_stashcash_getscbalance_proto_rawDescGZIP(), []int{0}
}

func (x *GetscbalanceRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type GetscbalanceResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        string                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data          *GetscbalanceResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetscbalanceResponse) Reset() {
	*x = GetscbalanceResponse{}
	mi := &file_stashcash_getscbalance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetscbalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetscbalanceResponse) ProtoMessage() {}

func (x *GetscbalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stashcash_getscbalance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetscbalanceResponse.ProtoReflect.Descriptor instead.
func (*GetscbalanceResponse) Descriptor() ([]byte, []int) {
	return file_stashcash_getscbalance_proto_rawDescGZIP(), []int{1}
}

func (x *GetscbalanceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetscbalanceResponse) GetData() *GetscbalanceResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetscbalanceResponse_Data struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Locked           float32                `protobuf:"fixed32,1,opt,name=locked,proto3" json:"locked,omitempty"`
	Unlocked         float32                `protobuf:"fixed32,2,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	Balance          float32                `protobuf:"fixed32,3,opt,name=balance,proto3" json:"balance,omitempty"`
	RupeeBalance     float32                `protobuf:"fixed32,4,opt,name=rupee_balance,json=rupeeBalance,proto3" json:"rupee_balance,omitempty"`
	UserGuide        bool                   `protobuf:"varint,5,opt,name=user_guide,json=userGuide,proto3" json:"user_guide,omitempty"`
	IsFrozen         bool                   `protobuf:"varint,6,opt,name=is_frozen,json=isFrozen,proto3" json:"is_frozen,omitempty"`
	ConversionFactor float32                `protobuf:"fixed32,7,opt,name=conversion_factor,json=conversionFactor,proto3" json:"conversion_factor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetscbalanceResponse_Data) Reset() {
	*x = GetscbalanceResponse_Data{}
	mi := &file_stashcash_getscbalance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetscbalanceResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetscbalanceResponse_Data) ProtoMessage() {}

func (x *GetscbalanceResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_stashcash_getscbalance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetscbalanceResponse_Data.ProtoReflect.Descriptor instead.
func (*GetscbalanceResponse_Data) Descriptor() ([]byte, []int) {
	return file_stashcash_getscbalance_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetscbalanceResponse_Data) GetLocked() float32 {
	if x != nil {
		return x.Locked
	}
	return 0
}

func (x *GetscbalanceResponse_Data) GetUnlocked() float32 {
	if x != nil {
		return x.Unlocked
	}
	return 0
}

func (x *GetscbalanceResponse_Data) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetscbalanceResponse_Data) GetRupeeBalance() float32 {
	if x != nil {
		return x.RupeeBalance
	}
	return 0
}

func (x *GetscbalanceResponse_Data) GetUserGuide() bool {
	if x != nil {
		return x.UserGuide
	}
	return false
}

func (x *GetscbalanceResponse_Data) GetIsFrozen() bool {
	if x != nil {
		return x.IsFrozen
	}
	return false
}

func (x *GetscbalanceResponse_Data) GetConversionFactor() float32 {
	if x != nil {
		return x.ConversionFactor
	}
	return 0
}

var File_stashcash_getscbalance_proto protoreflect.FileDescriptor

var file_stashcash_getscbalance_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x73, 0x74, 0x61, 0x73, 0x68, 0x63, 0x61, 0x73, 0x68, 0x2f, 0x67, 0x65, 0x74, 0x73,
	0x63, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x73, 0x74, 0x61, 0x73, 0x68, 0x63, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x65, 0x74, 0x73, 0x63, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x36, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x73, 0x63, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0xda,
	0x02, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x73, 0x63, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x45, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e,
	0x73, 0x74, 0x61, 0x73, 0x68, 0x63, 0x61, 0x73, 0x68, 0x2e, 0x67, 0x65, 0x74, 0x73, 0x63, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x67, 0x65, 0x74, 0x73, 0x63, 0x62, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xe2, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x75, 0x6e, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x72, 0x75, 0x70, 0x65, 0x65, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x72, 0x75, 0x70, 0x65, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x47, 0x75, 0x69, 0x64,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x66, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x12, 0x2b,
	0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_stashcash_getscbalance_proto_rawDescOnce sync.Once
	file_stashcash_getscbalance_proto_rawDescData []byte
)

func file_stashcash_getscbalance_proto_rawDescGZIP() []byte {
	file_stashcash_getscbalance_proto_rawDescOnce.Do(func() {
		file_stashcash_getscbalance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stashcash_getscbalance_proto_rawDesc), len(file_stashcash_getscbalance_proto_rawDesc)))
	})
	return file_stashcash_getscbalance_proto_rawDescData
}

var file_stashcash_getscbalance_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_stashcash_getscbalance_proto_goTypes = []any{
	(*GetscbalanceRequest)(nil),       // 0: stashcash.getscbalance.getscbalanceRequest
	(*GetscbalanceResponse)(nil),      // 1: stashcash.getscbalance.getscbalanceResponse
	(*GetscbalanceResponse_Data)(nil), // 2: stashcash.getscbalance.getscbalanceResponse.Data
}
var file_stashcash_getscbalance_proto_depIdxs = []int32{
	2, // 0: stashcash.getscbalance.getscbalanceResponse.data:type_name -> stashcash.getscbalance.getscbalanceResponse.Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stashcash_getscbalance_proto_init() }
func file_stashcash_getscbalance_proto_init() {
	if File_stashcash_getscbalance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stashcash_getscbalance_proto_rawDesc), len(file_stashcash_getscbalance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stashcash_getscbalance_proto_goTypes,
		DependencyIndexes: file_stashcash_getscbalance_proto_depIdxs,
		MessageInfos:      file_stashcash_getscbalance_proto_msgTypes,
	}.Build()
	File_stashcash_getscbalance_proto = out.File
	file_stashcash_getscbalance_proto_goTypes = nil
	file_stashcash_getscbalance_proto_depIdxs = nil
}
