// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: magneto/notifyinsurancepayment.proto

package magneto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyInsurancePaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     string  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	OrderId    string  `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId int32   `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Mode       *string `protobuf:"bytes,4,opt,name=mode,proto3,oneof" json:"mode,omitempty"`
	MetaData   string  `protobuf:"bytes,5,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	ClientId   string  `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *NotifyInsurancePaymentRequest) Reset() {
	*x = NotifyInsurancePaymentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magneto_notifyinsurancepayment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyInsurancePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyInsurancePaymentRequest) ProtoMessage() {}

func (x *NotifyInsurancePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magneto_notifyinsurancepayment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyInsurancePaymentRequest.ProtoReflect.Descriptor instead.
func (*NotifyInsurancePaymentRequest) Descriptor() ([]byte, []int) {
	return file_magneto_notifyinsurancepayment_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyInsurancePaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotifyInsurancePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *NotifyInsurancePaymentRequest) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *NotifyInsurancePaymentRequest) GetMode() string {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return ""
}

func (x *NotifyInsurancePaymentRequest) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

func (x *NotifyInsurancePaymentRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type NotifyInsurancePaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *NotifyInsurancePaymentResponse) Reset() {
	*x = NotifyInsurancePaymentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magneto_notifyinsurancepayment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyInsurancePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyInsurancePaymentResponse) ProtoMessage() {}

func (x *NotifyInsurancePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magneto_notifyinsurancepayment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyInsurancePaymentResponse.ProtoReflect.Descriptor instead.
func (*NotifyInsurancePaymentResponse) Descriptor() ([]byte, []int) {
	return file_magneto_notifyinsurancepayment_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyInsurancePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_magneto_notifyinsurancepayment_proto protoreflect.FileDescriptor

var file_magneto_notifyinsurancepayment_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x69, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x6f, 0x2e,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x69, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xcf, 0x01, 0x0a, 0x1d, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x49, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x38, 0x0a, 0x1e, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x49, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_magneto_notifyinsurancepayment_proto_rawDescOnce sync.Once
	file_magneto_notifyinsurancepayment_proto_rawDescData = file_magneto_notifyinsurancepayment_proto_rawDesc
)

func file_magneto_notifyinsurancepayment_proto_rawDescGZIP() []byte {
	file_magneto_notifyinsurancepayment_proto_rawDescOnce.Do(func() {
		file_magneto_notifyinsurancepayment_proto_rawDescData = protoimpl.X.CompressGZIP(file_magneto_notifyinsurancepayment_proto_rawDescData)
	})
	return file_magneto_notifyinsurancepayment_proto_rawDescData
}

var file_magneto_notifyinsurancepayment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_magneto_notifyinsurancepayment_proto_goTypes = []interface{}{
	(*NotifyInsurancePaymentRequest)(nil),  // 0: magneto.notifyinsurancepayment.notifyInsurancePaymentRequest
	(*NotifyInsurancePaymentResponse)(nil), // 1: magneto.notifyinsurancepayment.notifyInsurancePaymentResponse
}
var file_magneto_notifyinsurancepayment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_magneto_notifyinsurancepayment_proto_init() }
func file_magneto_notifyinsurancepayment_proto_init() {
	if File_magneto_notifyinsurancepayment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_magneto_notifyinsurancepayment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyInsurancePaymentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magneto_notifyinsurancepayment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyInsurancePaymentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_magneto_notifyinsurancepayment_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_magneto_notifyinsurancepayment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_magneto_notifyinsurancepayment_proto_goTypes,
		DependencyIndexes: file_magneto_notifyinsurancepayment_proto_depIdxs,
		MessageInfos:      file_magneto_notifyinsurancepayment_proto_msgTypes,
	}.Build()
	File_magneto_notifyinsurancepayment_proto = out.File
	file_magneto_notifyinsurancepayment_proto_rawDesc = nil
	file_magneto_notifyinsurancepayment_proto_goTypes = nil
	file_magneto_notifyinsurancepayment_proto_depIdxs = nil
}
