// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: banking/aa/initiatepennydrop.proto

package aa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PennyDropRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId    int64  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	IfscCode      string `protobuf:"bytes,3,opt,name=ifsc_code,json=ifscCode,proto3" json:"ifsc_code,omitempty"`
}

func (x *PennyDropRequest) Reset() {
	*x = PennyDropRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banking_aa_initiatepennydrop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PennyDropRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PennyDropRequest) ProtoMessage() {}

func (x *PennyDropRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_aa_initiatepennydrop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PennyDropRequest.ProtoReflect.Descriptor instead.
func (*PennyDropRequest) Descriptor() ([]byte, []int) {
	return file_banking_aa_initiatepennydrop_proto_rawDescGZIP(), []int{0}
}

func (x *PennyDropRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *PennyDropRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *PennyDropRequest) GetIfscCode() string {
	if x != nil {
		return x.IfscCode
	}
	return ""
}

type PennyDropResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PennyDropResponse) Reset() {
	*x = PennyDropResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_banking_aa_initiatepennydrop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PennyDropResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PennyDropResponse) ProtoMessage() {}

func (x *PennyDropResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banking_aa_initiatepennydrop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PennyDropResponse.ProtoReflect.Descriptor instead.
func (*PennyDropResponse) Descriptor() ([]byte, []int) {
	return file_banking_aa_initiatepennydrop_proto_rawDescGZIP(), []int{1}
}

func (x *PennyDropResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_banking_aa_initiatepennydrop_proto protoreflect.FileDescriptor

var file_banking_aa_initiatepennydrop_proto_rawDesc = []byte{
	0x0a, 0x22, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x61, 0x61, 0x2f, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x74, 0x65, 0x70, 0x65, 0x6e, 0x6e, 0x79, 0x64, 0x72, 0x6f, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x62, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x61,
	0x2e, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x70, 0x65, 0x6e, 0x6e, 0x79, 0x64, 0x72,
	0x6f, 0x70, 0x22, 0x77, 0x0a, 0x10, 0x70, 0x65, 0x6e, 0x6e, 0x79, 0x44, 0x72, 0x6f, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x66, 0x73, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x66, 0x73, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x70,
	0x65, 0x6e, 0x6e, 0x79, 0x44, 0x72, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_banking_aa_initiatepennydrop_proto_rawDescOnce sync.Once
	file_banking_aa_initiatepennydrop_proto_rawDescData = file_banking_aa_initiatepennydrop_proto_rawDesc
)

func file_banking_aa_initiatepennydrop_proto_rawDescGZIP() []byte {
	file_banking_aa_initiatepennydrop_proto_rawDescOnce.Do(func() {
		file_banking_aa_initiatepennydrop_proto_rawDescData = protoimpl.X.CompressGZIP(file_banking_aa_initiatepennydrop_proto_rawDescData)
	})
	return file_banking_aa_initiatepennydrop_proto_rawDescData
}

var file_banking_aa_initiatepennydrop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_banking_aa_initiatepennydrop_proto_goTypes = []interface{}{
	(*PennyDropRequest)(nil),  // 0: banking.aa.initiatepennydrop.pennyDropRequest
	(*PennyDropResponse)(nil), // 1: banking.aa.initiatepennydrop.pennyDropResponse
}
var file_banking_aa_initiatepennydrop_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_banking_aa_initiatepennydrop_proto_init() }
func file_banking_aa_initiatepennydrop_proto_init() {
	if File_banking_aa_initiatepennydrop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_banking_aa_initiatepennydrop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PennyDropRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_banking_aa_initiatepennydrop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PennyDropResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_banking_aa_initiatepennydrop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_banking_aa_initiatepennydrop_proto_goTypes,
		DependencyIndexes: file_banking_aa_initiatepennydrop_proto_depIdxs,
		MessageInfos:      file_banking_aa_initiatepennydrop_proto_msgTypes,
	}.Build()
	File_banking_aa_initiatepennydrop_proto = out.File
	file_banking_aa_initiatepennydrop_proto_rawDesc = nil
	file_banking_aa_initiatepennydrop_proto_goTypes = nil
	file_banking_aa_initiatepennydrop_proto_depIdxs = nil
}
