// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: customers/aa/getaatxnstatus.proto

package aa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAATransactionStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReferenceId string `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
}

func (x *GetAATransactionStatusRequest) Reset() {
	*x = GetAATransactionStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_aa_getaatxnstatus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAATransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAATransactionStatusRequest) ProtoMessage() {}

func (x *GetAATransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customers_aa_getaatxnstatus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAATransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAATransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_customers_aa_getaatxnstatus_proto_rawDescGZIP(), []int{0}
}

func (x *GetAATransactionStatusRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type GetAATransactionStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetAATransactionStatusResponse) Reset() {
	*x = GetAATransactionStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_aa_getaatxnstatus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAATransactionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAATransactionStatusResponse) ProtoMessage() {}

func (x *GetAATransactionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customers_aa_getaatxnstatus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAATransactionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAATransactionStatusResponse) Descriptor() ([]byte, []int) {
	return file_customers_aa_getaatxnstatus_proto_rawDescGZIP(), []int{1}
}

func (x *GetAATransactionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_customers_aa_getaatxnstatus_proto protoreflect.FileDescriptor

var file_customers_aa_getaatxnstatus_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x61, 0x2f, 0x67,
	0x65, 0x74, 0x61, 0x61, 0x74, 0x78, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x61,
	0x61, 0x2e, 0x67, 0x65, 0x74, 0x61, 0x61, 0x74, 0x78, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x42, 0x0a, 0x1d, 0x67, 0x65, 0x74, 0x41, 0x41, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x1e, 0x67, 0x65, 0x74, 0x41, 0x41, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_customers_aa_getaatxnstatus_proto_rawDescOnce sync.Once
	file_customers_aa_getaatxnstatus_proto_rawDescData = file_customers_aa_getaatxnstatus_proto_rawDesc
)

func file_customers_aa_getaatxnstatus_proto_rawDescGZIP() []byte {
	file_customers_aa_getaatxnstatus_proto_rawDescOnce.Do(func() {
		file_customers_aa_getaatxnstatus_proto_rawDescData = protoimpl.X.CompressGZIP(file_customers_aa_getaatxnstatus_proto_rawDescData)
	})
	return file_customers_aa_getaatxnstatus_proto_rawDescData
}

var file_customers_aa_getaatxnstatus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_customers_aa_getaatxnstatus_proto_goTypes = []interface{}{
	(*GetAATransactionStatusRequest)(nil),  // 0: customers.aa.getaatxnstatus.getAATransactionStatusRequest
	(*GetAATransactionStatusResponse)(nil), // 1: customers.aa.getaatxnstatus.getAATransactionStatusResponse
}
var file_customers_aa_getaatxnstatus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_customers_aa_getaatxnstatus_proto_init() }
func file_customers_aa_getaatxnstatus_proto_init() {
	if File_customers_aa_getaatxnstatus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_customers_aa_getaatxnstatus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAATransactionStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_aa_getaatxnstatus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAATransactionStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_customers_aa_getaatxnstatus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customers_aa_getaatxnstatus_proto_goTypes,
		DependencyIndexes: file_customers_aa_getaatxnstatus_proto_depIdxs,
		MessageInfos:      file_customers_aa_getaatxnstatus_proto_msgTypes,
	}.Build()
	File_customers_aa_getaatxnstatus_proto = out.File
	file_customers_aa_getaatxnstatus_proto_rawDesc = nil
	file_customers_aa_getaatxnstatus_proto_goTypes = nil
	file_customers_aa_getaatxnstatus_proto_depIdxs = nil
}
