// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.6
// source: kyc/fetchuanlist.proto

package kyc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchUanListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile     string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	CustomerId int32  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *FetchUanListRequest) Reset() {
	*x = FetchUanListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyc_fetchuanlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchUanListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUanListRequest) ProtoMessage() {}

func (x *FetchUanListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_fetchuanlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUanListRequest.ProtoReflect.Descriptor instead.
func (*FetchUanListRequest) Descriptor() ([]byte, []int) {
	return file_kyc_fetchuanlist_proto_rawDescGZIP(), []int{0}
}

func (x *FetchUanListRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *FetchUanListRequest) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type FetchUanListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UanList    []string `protobuf:"bytes,1,rep,name=uan_list,json=uanList,proto3" json:"uan_list,omitempty"`
	CustomerId int32    `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *FetchUanListResponse) Reset() {
	*x = FetchUanListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kyc_fetchuanlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchUanListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUanListResponse) ProtoMessage() {}

func (x *FetchUanListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_fetchuanlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUanListResponse.ProtoReflect.Descriptor instead.
func (*FetchUanListResponse) Descriptor() ([]byte, []int) {
	return file_kyc_fetchuanlist_proto_rawDescGZIP(), []int{1}
}

func (x *FetchUanListResponse) GetUanList() []string {
	if x != nil {
		return x.UanList
	}
	return nil
}

func (x *FetchUanListResponse) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

var File_kyc_fetchuanlist_proto protoreflect.FileDescriptor

var file_kyc_fetchuanlist_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6b, 0x79, 0x63, 0x2f, 0x66, 0x65, 0x74, 0x63, 0x68, 0x75, 0x61, 0x6e, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6b, 0x79, 0x63, 0x2e, 0x66, 0x65,
	0x74, 0x63, 0x68, 0x75, 0x61, 0x6e, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x13, 0x66, 0x65,
	0x74, 0x63, 0x68, 0x55, 0x61, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x14, 0x66, 0x65,
	0x74, 0x63, 0x68, 0x55, 0x61, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x61, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x61, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kyc_fetchuanlist_proto_rawDescOnce sync.Once
	file_kyc_fetchuanlist_proto_rawDescData = file_kyc_fetchuanlist_proto_rawDesc
)

func file_kyc_fetchuanlist_proto_rawDescGZIP() []byte {
	file_kyc_fetchuanlist_proto_rawDescOnce.Do(func() {
		file_kyc_fetchuanlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_kyc_fetchuanlist_proto_rawDescData)
	})
	return file_kyc_fetchuanlist_proto_rawDescData
}

var file_kyc_fetchuanlist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kyc_fetchuanlist_proto_goTypes = []interface{}{
	(*FetchUanListRequest)(nil),  // 0: kyc.fetchuanlist.fetchUanListRequest
	(*FetchUanListResponse)(nil), // 1: kyc.fetchuanlist.fetchUanListResponse
}
var file_kyc_fetchuanlist_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kyc_fetchuanlist_proto_init() }
func file_kyc_fetchuanlist_proto_init() {
	if File_kyc_fetchuanlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kyc_fetchuanlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchUanListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kyc_fetchuanlist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchUanListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kyc_fetchuanlist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kyc_fetchuanlist_proto_goTypes,
		DependencyIndexes: file_kyc_fetchuanlist_proto_depIdxs,
		MessageInfos:      file_kyc_fetchuanlist_proto_msgTypes,
	}.Build()
	File_kyc_fetchuanlist_proto = out.File
	file_kyc_fetchuanlist_proto_rawDesc = nil
	file_kyc_fetchuanlist_proto_goTypes = nil
	file_kyc_fetchuanlist_proto_depIdxs = nil
}
