// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.6
// source: customers/rpd/mockpayment.proto

package rpd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MockPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PaymentStatus string                 `protobuf:"bytes,2,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockPaymentRequest) Reset() {
	*x = MockPaymentRequest{}
	mi := &file_customers_rpd_mockpayment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockPaymentRequest) ProtoMessage() {}

func (x *MockPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customers_rpd_mockpayment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockPaymentRequest.ProtoReflect.Descriptor instead.
func (*MockPaymentRequest) Descriptor() ([]byte, []int) {
	return file_customers_rpd_mockpayment_proto_rawDescGZIP(), []int{0}
}

func (x *MockPaymentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MockPaymentRequest) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

type MockPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockPaymentResponse) Reset() {
	*x = MockPaymentResponse{}
	mi := &file_customers_rpd_mockpayment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockPaymentResponse) ProtoMessage() {}

func (x *MockPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customers_rpd_mockpayment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockPaymentResponse.ProtoReflect.Descriptor instead.
func (*MockPaymentResponse) Descriptor() ([]byte, []int) {
	return file_customers_rpd_mockpayment_proto_rawDescGZIP(), []int{1}
}

func (x *MockPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MockPaymentResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_customers_rpd_mockpayment_proto protoreflect.FileDescriptor

var file_customers_rpd_mockpayment_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2f, 0x72, 0x70, 0x64, 0x2f,
	0x6d, 0x6f, 0x63, 0x6b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x19, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2e, 0x72, 0x70, 0x64,
	0x2e, 0x6d, 0x6f, 0x63, 0x6b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x12,
	0x6d, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4a, 0x0a, 0x13, 0x6d, 0x6f, 0x63, 0x6b,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_customers_rpd_mockpayment_proto_rawDescOnce sync.Once
	file_customers_rpd_mockpayment_proto_rawDescData []byte
)

func file_customers_rpd_mockpayment_proto_rawDescGZIP() []byte {
	file_customers_rpd_mockpayment_proto_rawDescOnce.Do(func() {
		file_customers_rpd_mockpayment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customers_rpd_mockpayment_proto_rawDesc), len(file_customers_rpd_mockpayment_proto_rawDesc)))
	})
	return file_customers_rpd_mockpayment_proto_rawDescData
}

var file_customers_rpd_mockpayment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_customers_rpd_mockpayment_proto_goTypes = []any{
	(*MockPaymentRequest)(nil),  // 0: customers.rpd.mockpayment.mockPaymentRequest
	(*MockPaymentResponse)(nil), // 1: customers.rpd.mockpayment.mockPaymentResponse
}
var file_customers_rpd_mockpayment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_customers_rpd_mockpayment_proto_init() }
func file_customers_rpd_mockpayment_proto_init() {
	if File_customers_rpd_mockpayment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customers_rpd_mockpayment_proto_rawDesc), len(file_customers_rpd_mockpayment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customers_rpd_mockpayment_proto_goTypes,
		DependencyIndexes: file_customers_rpd_mockpayment_proto_depIdxs,
		MessageInfos:      file_customers_rpd_mockpayment_proto_msgTypes,
	}.Build()
	File_customers_rpd_mockpayment_proto = out.File
	file_customers_rpd_mockpayment_proto_goTypes = nil
	file_customers_rpd_mockpayment_proto_depIdxs = nil
}
